name: Update List Count Banner

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  update-banner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Count list items and update README
        run: python3 src/update_banner.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update list count in README" -a || echo "No changes to commit"
          git push origin HEAD:master  # Ensure this matches your repository's default branch
      
    

